language: objective-c
xcode_project: Franz.xcodeproj
xcode_scheme: franz-Package
osx_image: xcode9.3
sudo: required
services:
  - docker
script:
  - set -o pipefail
  - xcodebuild test -scheme Franz -skip-testing:DockerTests | xcpretty
