version: '3'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    volumes:
      - .:/conf
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /conf
    environment:
      KAFKA_OPTS: -Djava.security.auth.login.config=kafka_server_jaas.conf
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9092
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
